#!/bin/sh

set -o errexit
set -o nounset

mysql_ready() {
python << END
import os
import sys
import pymysql

try:
    pymysql.connect(
        host=os.environ['MYSQL_HOST'],
        port=int(os.environ['MYSQL_PORT']),
        user=os.environ['MYSQL_USER'],
        password=os.environ['MYSQL_PASSWORD'],
        database=os.environ['MYSQL_DATABASE'])
except pymysql.err.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo 'Esperando que el servidor MySQL este disponible...'
  sleep 1
done
>&2 echo 'MySQL esta disponible'

exec "$@"
